// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwyXAbtPFkoVzb0bA33eiI28vc12GbHVc',
    appId: '1:782601360703:android:484c950efadf7837e4af8a',
    messagingSenderId: '782601360703',
    projectId: 'auth-router-context-36be7',
    storageBucket: 'auth-router-context-36be7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4hSRKBY3NRNpiBu1zApEaDZWIg__khoc',
    appId: '1:782601360703:ios:141ba448b9c660b8e4af8a',
    messagingSenderId: '782601360703',
    projectId: 'auth-router-context-36be7',
    storageBucket: 'auth-router-context-36be7.firebasestorage.app',
    androidClientId: '782601360703-280k3r2iu3kpv42a7kjcfcckvrgdtdri.apps.googleusercontent.com',
    iosClientId: '782601360703-jj98l7c94t3ac0o8i1j4fdjck4mlsdmg.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartFaceAttendance',
  );
}
